hosts: [
  { host_ip: "192.168.0.30", host_name: "cd"},
  { host_ip: "192.168.0.31", host_name: "sentinel-1"},
  { host_ip: "192.168.0.32", host_name: "sentinel-2"},
  { host_ip: "192.168.0.33", host_name: "sentinel-3"}
]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     { src: "centos.sshd_config", dest: "/etc/ssh/sshd_config" },
  ]