hosts: [
  { host_ip: "192.168.1.50", host_name: "cd"},
  { host_ip: "192.168.1.57", host_name: "hadoop-1"},
  { host_ip: "192.168.1.58", host_name: "hadoop-2"},
  { host_ip: "192.168.1.59", host_name: "hadoop-3"}
]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     { src: "centos.sshd_config", dest: "/etc/ssh/sshd_config" },
  ]
