# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/vagrant"
  end
  config.vm.define "cd" do |d|
    d.vm.box ="ubuntu/bionic64" 
    d.vm.hostname = "cd"
    d.vm.network "private_network", ip: "192.168.0.30"
    d.vm.provision :shell, path: "scripts/bootstrap_ansible.sh"
    d.vm.provision :shell, inline: "PYTHONUNBUFFERED=1 ansible-playbook /vagrant/ansible/cd.yml -c local"
    d.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
  end
  (1..3).each do |i|
    config.vm.define "sentinel-#{i}" do |d|
      d.vm.box ="ubuntu/bionic64" 
      d.vm.hostname = "sentinel-#{i}"
      d.vm.network "private_network", ip: "192.168.0.3#{i}"      
      d.vm.provider "virtualbox" do |v|
        v.memory = 2048
      end
      d.vm.provision :shell, inline: "PYTHONUNBUFFERED=1 sudo apt install -y python"
    end
  end  
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
   if Vagrant.has_plugin?("vagrant-vbguest")
     config.vbguest.auto_update = false
     config.vbguest.no_install = false
     config.vbguest.no_remote = false
   end
end
